//
// Created by Hans Johnson on 2026-02-14.
// Modified by Noah Krchak

#include "SimpleThresholdCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()
#include "itkBinaryThresholdImageFilter.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
using PixelType =  signed short; // This is pixel type was chosen based on the README.md specifying that the input image was signed short data type
constexpr int Dim = 3;

// I/O Image Types
using InputImageType = itk::Image<PixelType, Dim>;
using OutputImageType = itk::Image<PixelType, Dim>;

// Reader and Writer Types
using ReaderType = itk::ImageFileReader<InputImageType>;
using WriterType = itk::ImageFileWriter<OutputImageType>;

// Binary Threshold Filter Type
using BinaryThresholdImageFilterType = itk::BinaryThresholdImageFilter<InputImageType, OutputImageType>;

int main (int argc, char * argv[])
{
  PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h



  std::cout << "The input volume is: " << input << std::endl;
  std::cout << "The output volume is: " << output << std::endl;


  try{
     typename ReaderType::Pointer imageReader = ReaderType::New();
     typename WriterType::Pointer imageWriter = WriterType::New();

     imageReader->SetFileName(input);
     imageWriter->SetFileName(output);

     typename InputImageType::Pointer inputImage = imageReader->GetOutput();
     typename BinaryThresholdImageFilterType::Pointer binaryThresholdFilter = BinaryThresholdImageFilterType::New();

     // Explicitly casting SEM parameters from integer type to the PixelType to avoid warning about implicit conversion
     //Set Threshold Range
     binaryThresholdFilter->SetLowerThreshold(static_cast<PixelType>(lowThreshold));
     binaryThresholdFilter->SetUpperThreshold(static_cast<PixelType>(highThreshold));

     //Set Inside threshold value and outside threshold value
     binaryThresholdFilter->SetInsideValue(static_cast<PixelType>(insideValue));
     binaryThresholdFilter->SetOutsideValue(static_cast<PixelType>(outsideValue));

     binaryThresholdFilter->SetInput(inputImage);
     typename OutputImageType::Pointer outputImage = binaryThresholdFilter->GetOutput();

     imageWriter->SetInput(outputImage);
     imageWriter->Update();

  }catch(itk::ExceptionObject & err){
    std::cerr << "ExceptionObject caught !" << std::endl;
    std::cerr << err << std::endl;
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
