

#include "DOGCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()
#include "itkSmoothingRecursiveGaussianImageFilter.h"
#include "itkSubtractImageFilter.h"
#include "itkRescaleIntensityImageFilter.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"

using InputPixelType =  short;
using IntermediatePixelType =  short;
using OutputPixelType = unsigned char;
constexpr int Dim = 3;

constexpr int OutputImageMin = 0;
constexpr int OutputImageMax = 255;

// I/O Image Types
using InputImageType = itk::Image<InputPixelType, Dim>;
using IntermediateImageType = itk::Image<IntermediatePixelType, Dim>;
using OutputImageType = itk::Image<OutputPixelType, Dim>;

// Reader and Writer Types
using ReaderType = itk::ImageFileReader<InputImageType>;
using WriterType = itk::ImageFileWriter<OutputImageType>;

// Recursive Gaussian Type, Subtract Filter Type and Rescale Intensity Type for Difference of Gaussians (DOG)
using SmoothingRecursiveGaussianFilterType = itk::SmoothingRecursiveGaussianImageFilter<InputImageType, IntermediateImageType>;
using SubtractFilterType = itk::SubtractImageFilter<IntermediateImageType , IntermediateImageType>;
using RescaleIntensityFilterType = itk::RescaleIntensityImageFilter<IntermediateImageType, OutputImageType>;

int main (int argc, char * argv[])
{
  PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h




  std::cout << "The input volume is: " << input << std::endl;
  std::cout << "The output volume is: " << output << std::endl;


  if(sigma1 == sigma2)
  {
    std::cerr << "Error: Sigma 1 and Sigma 2 cannot be equal" << std::endl;
    return EXIT_FAILURE;
  }
  try{
     typename ReaderType::Pointer imageReader = ReaderType::New();
     typename WriterType::Pointer imageWriter = WriterType::New();

     imageReader->SetFileName(input);
     imageWriter->SetFileName(output);

     typename InputImageType::Pointer inputImage = imageReader->GetOutput();
     typename SmoothingRecursiveGaussianFilterType::Pointer gaussianLPF1 = SmoothingRecursiveGaussianFilterType::New();
     typename SmoothingRecursiveGaussianFilterType::Pointer gaussianLPF2 = SmoothingRecursiveGaussianFilterType::New();
     //Set input and sigma for first Gaussian LPF
     gaussianLPF1->SetInput(inputImage);
     gaussianLPF1->SetSigma(sigma1);
     //Set input and sigma for second Gaussian LPF
     gaussianLPF2->SetInput(inputImage);
     gaussianLPF2->SetSigma(sigma2);

     //Grab output of Gaussian LPFs
     typename IntermediateImageType::Pointer outputGaussian1Image = gaussianLPF1->GetOutput();
     typename IntermediateImageType::Pointer outputGaussian2Image = gaussianLPF2->GetOutput();

     typename SubtractFilterType::Pointer subtractFilter = SubtractFilterType::New();

     //Set input of subtract filter to output of gaussian LPFs
     subtractFilter->SetInput1(outputGaussian1Image);
     subtractFilter->SetInput2(outputGaussian2Image);

     typename IntermediateImageType::Pointer outputDOGImage = subtractFilter->GetOutput();

     typename RescaleIntensityFilterType::Pointer rescaleIntensityFilter = RescaleIntensityFilterType::New();

     //Rescale intensity to match unsigned char min and max intensities (0 and 255 respectively)
     rescaleIntensityFilter->SetInput(outputDOGImage);
     rescaleIntensityFilter->SetOutputMinimum(OutputImageMin);
     rescaleIntensityFilter->SetOutputMaximum(OutputImageMax);

     typename OutputImageType::Pointer outputImage = rescaleIntensityFilter->GetOutput();
     //Write image to disk
     imageWriter->SetInput(outputImage);
     imageWriter->Update();

  }catch(itk::ExceptionObject & err){
    std::cerr << "ExceptionObject caught !" << std::endl;
    std::cerr << err << std::endl;
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
