//
// Created by Hans Johnson on 2026-02-14.
//

#include "DOGCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()
#include "itkRecursiveGaussianImageFilter.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
using InputPixelType =  short;
using OutputPixelType = unsigned char;
constexpr int Dim = 3;

// I/O Image Types
using InputImageType = itk::Image<InputPixelType, Dim>;
using OutputImageType = itk::Image<OutputPixelType, Dim>;

// Reader and Writer Types
using ReaderType = itk::ImageFileReader<InputImageType>;
using WriterType = itk::ImageFileWriter<OutputImageType>;

// Binary Threshold Filter Type
using RecursiveGaussianFilterType = itk::RecursiveGaussianImageFilter<InputImageType, InputImageType>;

int main (int argc, char * argv[])
{
  PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h



  std::cout << "The number of iterations is: " << numberOfIterations
            << std::endl;
  std::cout << "The input volume is: " << input << std::endl;
  std::cout << "The output volume is: " << output << std::endl;


  try{
     typename ReaderType::Pointer imageReader = ReaderType::New();
     typename WriterType::Pointer imageWriter = WriterType::New();

     imageReader->SetFileName(input);
     imageWriter->SetFileName(output);

     typename InputImageType::Pointer inputImage = imageReader->GetOutput();
     typename RecursiveGaussianFilterType::Pointer gaussianLPF1 = RecursiveGaussianFilterType::New();
     typename RecursiveGaussianFilterType::Pointer gaussianLPF2 = RecursiveGaussianFilterType::New();
     //Set input and sigma for Gaussian LPF
     gaussianLPF1->SetInput(inputImage);
     gaussianLPF1->SetSigma(sigma1);

     gaussianLPF2->SetInput(inputImage);
     gaussianLPF2->SetSigma(sigma2);

     typename InputImageType::Pointer outputGaussian1Image = gaussianLPF1->GetOutput();
     typename InputImageType::Pointer outputGaussian2Image = gaussianLPF2->GetOutput();

     //Write image to disk
     //imageWriter->SetInput(outputImage);
     imageWriter->Update();

  }catch(itk::ExceptionObject & err){
    std::cerr << "ExceptionObject caught !" << std::endl;
    std::cerr << err << std::endl;
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
