//
// Created by Hans Johnson on 2026-02-14.
//

#include "GradientADCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()
#include "itkGradientAnisotropicDiffusionImageFilter.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"

using InputPixelType =  double;
using OutputPixelType = double;
constexpr int Dim = 3;


// I/O Image Types
using InputImageType = itk::Image<InputPixelType, Dim>;

using OutputImageType = itk::Image<OutputPixelType, Dim>;

// Reader and Writer Types
using ReaderType = itk::ImageFileReader<InputImageType>;
using WriterType = itk::ImageFileWriter<OutputImageType>;

// Binary Threshold Filter Type
using GradientAnisotropicDiffusionFilterType = itk::GradientAnisotropicDiffusionImageFilter<InputImageType,OutputImageType>;


int main (int argc, char * argv[])
{
  PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h




  std::cout << "The input volume is: " << input << std::endl;
  std::cout << "The output volume is: " << output << std::endl;



  try{
     typename ReaderType::Pointer imageReader = ReaderType::New();
     typename WriterType::Pointer imageWriter = WriterType::New();

     imageReader->SetFileName(input);
     imageWriter->SetFileName(output);

     typename InputImageType::Pointer inputImage = imageReader->GetOutput();
     typename GradientAnisotropicDiffusionFilterType::Pointer gradientAD = GradientAnisotropicDiffusionFilterType::New();

     gradientAD->SetInput(inputImage);
     gradientAD->SetConductanceParameter(conductance);
     gradientAD->SetTimeStep(timeStep);
     gradientAD->SetNumberOfIterations(iterations);

     typename OutputImageType::Pointer outputImage = gradientAD->GetOutput();

     //Write image to disk
     imageWriter->SetInput(outputImage);
     imageWriter->Update();

  }catch(itk::ExceptionObject & err){
    std::cerr << "ExceptionObject caught !" << std::endl;
    std::cerr << err << std::endl;
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
