
#include "GaussianLPFCLP.h" // <-- NOTE THIS FILE WAS AUTO GENERATED by GENERATECLP()
#include "itkSmoothingRecursiveGaussianImageFilter.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
using PixelType =  short;
constexpr int Dim = 3;

// I/O Image Types
using InputImageType = itk::Image<PixelType, Dim>;
using OutputImageType = itk::Image<PixelType, Dim>;

// Reader and Writer Types
using ReaderType = itk::ImageFileReader<InputImageType>;
using WriterType = itk::ImageFileWriter<OutputImageType>;

// Recursive Gaussian Filter Type
using SmoothingRecursiveGaussianFilterType = itk::SmoothingRecursiveGaussianImageFilter<InputImageType, OutputImageType>;

int main (int argc, char * argv[])
{
  PARSE_ARGS;  // <--- This is always the first line and is defined in SimpleThresholdCLP.h




  std::cout << "The input volume is: " << input << std::endl;
  std::cout << "The output volume is: " << output << std::endl;


  try{
     typename ReaderType::Pointer imageReader = ReaderType::New();
     typename WriterType::Pointer imageWriter = WriterType::New();

     imageReader->SetFileName(input);
     imageWriter->SetFileName(output);

     typename InputImageType::Pointer inputImage = imageReader->GetOutput();
     typename SmoothingRecursiveGaussianFilterType::Pointer gaussianLPF = SmoothingRecursiveGaussianFilterType::New();

     //Set input and sigma for Gaussian LPF
     gaussianLPF->SetInput(inputImage);
     gaussianLPF->SetSigma(sigma);

     typename OutputImageType::Pointer outputImage = gaussianLPF->GetOutput();

     //Write image to disk
     imageWriter->SetInput(outputImage);
     imageWriter->Update();

  }catch(itk::ExceptionObject & err){
    std::cerr << "ExceptionObject caught !" << std::endl;
    std::cerr << err << std::endl;
    return EXIT_FAILURE;
  }
  return EXIT_SUCCESS;
}
